spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:app
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect