server:
  port: 8989

# Creates the table on startup
spring:
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:/org/springframework/batch/core/schema-h2.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.hibernate: ERROR