version: '3.8'
services:
### PG database
  postgres:
    image: postgres
    # This is required when connecting from another container jdbc:postgresql://postgresdb:5432/pg_account
    # container_name: postgresdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=pg_account
      - PGDATA=/var/lib/postgresql/data/pgdata
    expose:
      - 5432

### MYSQL database
  mysql:
    image: mysql
    # This is required when connecting from another container
    #container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sql_account
    expose:
      - 3306